# temp.conf: create a directory for temporary user data
# see tmpfiles.d(5), systemd-tmpfiles(8)

#Type   Path                                      Mode    UID   GID   Age   Argument
d       %h/Temp                                   01755   -     -     10d

