pulse.rules = [
    {
        # ZOOM Audio fix
        matches = [ { application.name = "ZOOM VoiceEngine" } ]
        actions = {
            update-props = {
                pulse.min.quantum      = 1024/48000     # 21ms
            }
        }
    }
}
